### ISSUE TITLE
Introduce `rust-toolchain.toml`

### ISSUE THREAD

**Issue by mversic** [hyperledger-iroha/iroha#5051]
How about we commit a `rust-toolchain.toml` file so that the developers get the rust version corresponding to what we have in CI right away?

```toml
[toolchain]
channel = "nightly-2024-09-09"
```

_Originally posted by @DCNick3 in https://github.com/hyperledger/iroha/issues/5047#issuecomment-2339796260_
