### ISSUE TITLE
[BUG] "This peer is faulty." "Restarting consensus(internal bug). Report to developers" No new blocks get created.

### ISSUE THREAD

**Issue by matisalimbene** [hyperledger-iroha/iroha#5230]
### OS and Environment

hyperledger/iroha2:stable-2.0.0-pre-rc.20

### GIT commit hash

5d44d59

### Minimum working example / Steps to reproduce

I'm simply running an Iroha2 network and then adding new nodes. Everything seems to work, then it doesn't. Once I start getting the "Faulty peer" and "Restaring consensus (internal bug)" error, the consensus fails and no new blocks get created.

### Actual result

2m2024-10-23T17:15:03.735738Z0m 31mERROR0m 2miroha_core::sumeragi0m2m:0m This peer is faulty. Incoming control messages have to be dropped due to low processing speed. 3merror0m2m=0m"Full(..)"
2m2024-10-23T17:15:08.559967Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Rotating the entire topology. 3maddr0m2m=0miroha3:1340
2m2024-10-23T17:15:08.560120Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::network_topology0m2m:0m Restarting consensus(internal bug). Report to developers

### Expected result

2024-10-22T11:35:33.453135Z  INFO consensus: iroha_core::sumeragi::main_loop: Committing block addr=iroha0:1337 role=ProxyTail block_height=5 block_hash=6e86dd99781773aa26fc893b369061e95ef3e9ab361e2e412c515a662e88b257

### Logs

<details>
  <summary>Log contents</summary>
  
  ```json
2m2024-10-23T15:39:31.663932Z0m 33m WARN0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block not committed in due time, requesting view change... 3mpeer_public_key0m2m=0med012017D319438B343995848F112BEB38695D3AA696C71257D52B12D630FD0099B792 3mrole0m2m=0mLeader 3mblock0m2m=0m75c88aa9bac3312a23865f8529afbc11539ac677f196d10e06910ba6bae7f72b
2m2024-10-23T15:39:31.704674Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Rotating the entire topology. 3maddr0m2m=0miroha3:1340
2m2024-10-23T15:39:31.705113Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m View change updated 3maddr0m2m=0miroha3:1340 3mrole0m2m=0mObservingPeer 3mcurrent_view_change_index0m2m=0m9
2m2024-10-23T15:39:31.757324Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block validated 3maddr0m2m=0miroha3:1340 3mblock_hash0m2m=0m88f388685b39953a58311d8ec6bbac0f927785e71f58f9c8c3fb73198c844d9f
2m2024-10-23T15:39:31.757576Z0m 33m WARN0m 1mrun0m1m{0m3mlisten_addr0m2m=0miroha3:1340 3mpublic_key0m2m=0med012017D319438B343995848F112BEB38695D3AA696C71257D52B12D630FD0099B7921m}0m2m:0m 2miroha_p2p::network0m2m:0m Peer not found. Message not sent. 3mpeer0m2m=0med0120B71E8ABEB649763813310D9E1EDCE1DA74D129BD68086BE55A5103DF64610358@@100.112.24.100:1347
2m2024-10-23T15:39:31.757644Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block signed and forwarded 3maddr0m2m=0miroha3:1340 3mblock_hash0m2m=0m88f388685b39953a58311d8ec6bbac0f927785e71f58f9c8c3fb73198c844d9f
2m2024-10-23T15:39:37.709196Z0m 33m WARN0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block not committed in due time, requesting view change... 3mpeer_public_key0m2m=0med012017D319438B343995848F112BEB38695D3AA696C71257D52B12D630FD0099B792 3mrole0m2m=0mObservingPeer 3mblock0m2m=0m88f388685b39953a58311d8ec6bbac0f927785e71f58f9c8c3fb73198c844d9f
2m2024-10-23T15:39:37.789213Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Rotating the entire topology. 3maddr0m2m=0miroha3:1340
2m2024-10-23T15:39:37.789670Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m View change updated 3maddr0m2m=0miroha3:1340 3mrole0m2m=0mObservingPeer 3mcurrent_view_change_index0m2m=0m10
2m2024-10-23T15:39:37.852438Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block validated 3maddr0m2m=0miroha3:1340 3mblock_hash0m2m=0m6f3bd1d210766f784edfcc1650d6148015fe95f225bd547490f0206fa806f5d5
2m2024-10-23T15:39:37.852567Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block signed and forwarded 3maddr0m2m=0miroha3:1340 3mblock_hash0m2m=0m6f3bd1d210766f784edfcc1650d6148015fe95f225bd547490f0206fa806f5d5
2m2024-10-23T15:39:43.805274Z0m 33m WARN0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block not committed in due time, requesting view change... 3mpeer_public_key0m2m=0med012017D319438B343995848F112BEB38695D3AA696C71257D52B12D630FD0099B792 3mrole0m2m=0mObservingPeer 3mblock0m2m=0m6f3bd1d210766f784edfcc1650d6148015fe95f225bd547490f0206fa806f5d5
2m2024-10-23T15:39:43.860765Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Rotating the entire topology. 3maddr0m2m=0miroha3:1340
2m2024-10-23T15:39:43.860945Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m View change updated 3maddr0m2m=0miroha3:1340 3mrole0m2m=0mProxyTail 3mcurrent_view_change_index0m2m=0m11
2m2024-10-23T15:39:49.867767Z0m 33m WARN0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m No block produced in due time, requesting view change... 3mpeer_public_key0m2m=0med012017D319438B343995848F112BEB38695D3AA696C71257D52B12D630FD0099B792 3mrole0m2m=0mProxyTail
2m2024-10-23T15:39:49.929823Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Rotating the entire topology. 3maddr0m2m=0miroha3:1340
2m2024-10-23T15:39:49.929919Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::network_topology0m2m:0m Restarting consensus(internal bug). Report to developers
2m2024-10-23T15:39:49.930290Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m View change updated 3maddr0m2m=0miroha3:1340 3mrole0m2m=0mObservingPeer 3mcurrent_view_change_index0m2m=0m12
2m2024-10-23T15:39:55.936268Z0m 33m WARN0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m No block produced in due time, requesting view change... 3mpeer_public_key0m2m=0med012017D319438B343995848F112BEB38695D3AA696C71257D52B12D630FD0099B792 3mrole0m2m=0mObservingPeer
2m2024-10-23T15:39:56.019971Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Rotating the entire topology. 3maddr0m2m=0miroha3:1340
2m2024-10-23T15:39:56.020033Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::network_topology0m2m:0m Restarting consensus(internal bug). Report to developers
2m2024-10-23T15:39:56.020158Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m View change updated 3maddr0m2m=0miroha3:1340 3mrole0m2m=0mObservingPeer 3mcurrent_view_change_index0m2m=0m13
2m2024-10-23T15:39:56.083151Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block validated 3maddr0m2m=0miroha3:1340 3mblock_hash0m2m=0m408e34d457e753c5f69291f35127581004d23f8c603a0eb957680ce8ac4480d1
2m2024-10-23T15:39:56.083661Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block signed and forwarded 3maddr0m2m=0miroha3:1340 3mblock_hash0m2m=0m408e34d457e753c5f69291f35127581004d23f8c603a0eb957680ce8ac4480d1
2m2024-10-23T15:40:02.028544Z0m 33m WARN0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block not committed in due time, requesting view change... 3mpeer_public_key0m2m=0med012017D319438B343995848F112BEB38695D3AA696C71257D52B12D630FD0099B792 3mrole0m2m=0mObservingPeer 3mblock0m2m=0m408e34d457e753c5f69291f35127581004d23f8c603a0eb957680ce8ac4480d1
2m2024-10-23T15:40:02.108345Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Rotating the entire topology. 3maddr0m2m=0miroha3:1340
2m2024-10-23T15:40:02.108490Z0m 31mERROR0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::network_topology0m2m:0m Restarting consensus(internal bug). Report to developers
2m2024-10-23T15:40:02.108723Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m View change updated 3maddr0m2m=0miroha3:1340 3mrole0m2m=0mLeader 3mcurrent_view_change_index0m2m=0m14
2m2024-10-23T15:40:02.108790Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Creating block... 3maddr0m2m=0miroha3:1340 3mtxns0m2m=0m1
2m2024-10-23T15:40:02.111319Z0m 32m INFO0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block created 3maddr0m2m=0miroha3:1340 3mcreated_in_ms0m2m=0m2 3mblock_payload_hash0m2m=0me01c9e53fd2a425f2e854d15060d6b23a369ba3349ef9f2e756387ec64292ee5
2m2024-10-23T15:40:08.128043Z0m 33m WARN0m 1mconsensus0m2m:0m 2miroha_core::sumeragi::main_loop0m2m:0m Block not committed in due time, requesting view change... 3mpeer_public_key0m2m=0med012017D319438B343995848F112BEB38695D3AA696C71257D52B12D630FD0099B792 3mrole0m2m=0mLeader 3mblock0m2m=0me01c9e53fd2a425f2e854d15060d6b23a369ba3349ef9f2e756387ec64292ee5
2m2
  ```
</details>

### Notes

Initially I start the network with a docker compose file as follows. After that is up and running, new peers start to join, until it the error appears:
  ```yaml
services:
  iroha0:
    container_name: iroha0
    image: hyperledger/iroha2:stable-2.0.0-pre-rc.20
    environment:
      TORII_P2P_ADDR: iroha0:1337
      TORII_API_URL: iroha0:8080
      TORII_TELEMETRY_URL: iroha0:8180
      IROHA_PUBLIC_KEY: ${IROHA_PUBLIC_KEY_0}
      IROHA_PRIVATE_KEY: ${IROHA_PRIVATE_KEY_0}
      SUMERAGI_TRUSTED_PEERS: ${SUMERAGI_TRUSTED_PEERS}
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: ${IROHA_GENESIS_ACCOUNT_PUBLIC_KEY}
      IROHA_GENESIS_ACCOUNT_PRIVATE_KEY: ${IROHA_GENESIS_ACCOUNT_PRIVATE_KEY}
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_COUNT_LIMIT: 100
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_PERIOD_MS: 500
      IROHA_GENESIS_GENESIS_SUBMISSION_DELAY_MS: 1000
      IROHA_CLIENT_CONFIG: /config/config_cli_iroha0.json
      KURA_BLOCK_STORE_PATH: /opt/iroha_data/storage
    ports:
      - "1337:1337"
      - "8080:8080"
      - "8180:8180"
    user: root
    volumes:
      - iroha0-alpha-vol:/opt/iroha_data/storage:rw
      - "./configs/peer/alpha:/config"
    init: true
    command: iroha --submit-genesis

  iroha1:
    container_name: iroha1
    image: hyperledger/iroha2:stable-2.0.0-pre-rc.20
    environment:
      TORII_P2P_ADDR: iroha1:1338
      TORII_API_URL: iroha1:8081
      TORII_TELEMETRY_URL: iroha1:8181
      IROHA_PUBLIC_KEY: ${IROHA_PUBLIC_KEY_1}
      IROHA_PRIVATE_KEY: ${IROHA_PRIVATE_KEY_1}
      SUMERAGI_TRUSTED_PEERS: ${SUMERAGI_TRUSTED_PEERS}
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: ${IROHA_GENESIS_ACCOUNT_PUBLIC_KEY}
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_COUNT_LIMIT: 100
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_PERIOD_MS: 500
      IROHA_GENESIS_GENESIS_SUBMISSION_DELAY_MS: 1000
      IROHA_CLIENT_CONFIG: /config/config_cli_iroha0.json
      KURA_BLOCK_STORE_PATH: /opt/iroha_data/storage
    ports:
      - "1338:1338"
      - "8081:8081"
      - "8181:8181"
    user: root
    volumes:
      - iroha1-alpha-vol:/opt/iroha_data/storage:rw
      - "./configs/peer/alpha:/config"
    init: true

  iroha2:
    container_name: iroha2
    image: hyperledger/iroha2:stable-2.0.0-pre-rc.20
    environment:
      TORII_P2P_ADDR: iroha2:1339
      TORII_API_URL: iroha2:8082
      TORII_TELEMETRY_URL: iroha2:8182
      IROHA_PUBLIC_KEY: ${IROHA_PUBLIC_KEY_2}
      IROHA_PRIVATE_KEY: ${IROHA_PRIVATE_KEY_2}
      SUMERAGI_TRUSTED_PEERS: ${SUMERAGI_TRUSTED_PEERS}
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: ${IROHA_GENESIS_ACCOUNT_PUBLIC_KEY}
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_COUNT_LIMIT: 100
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_PERIOD_MS: 500
      IROHA_GENESIS_GENESIS_SUBMISSION_DELAY_MS: 1000
      IROHA_CLIENT_CONFIG: /config/config_cli_iroha0.json
      KURA_BLOCK_STORE_PATH: /opt/iroha_data/storage
    ports:
      - "1339:1339"
      - "8082:8082"
      - "8182:8182"
    user: root
    volumes:
      - iroha2-alpha-vol:/opt/iroha_data/storage:rw
      - "./configs/peer/alpha:/config"
    init: true

  iroha3:
    container_name: iroha3
    image: hyperledger/iroha2:stable-2.0.0-pre-rc.20
    environment:
      TORII_P2P_ADDR: iroha3:1340
      TORII_API_URL: iroha3:8083
      TORII_TELEMETRY_URL: iroha3:8183
      IROHA_PUBLIC_KEY: ${IROHA_PUBLIC_KEY_3}
      IROHA_PRIVATE_KEY: ${IROHA_PRIVATE_KEY_3}
      SUMERAGI_TRUSTED_PEERS: ${SUMERAGI_TRUSTED_PEERS}
      IROHA_GENESIS_ACCOUNT_PUBLIC_KEY: ${IROHA_GENESIS_ACCOUNT_PUBLIC_KEY}
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_COUNT_LIMIT: 100
      IROHA_GENESIS_WAIT_FOR_PEERS_RETRY_PERIOD_MS: 500
      IROHA_GENESIS_GENESIS_SUBMISSION_DELAY_MS: 1000
      IROHA_CLIENT_CONFIG: /config/config_cli_iroha0.json
      KURA_BLOCK_STORE_PATH: /opt/iroha_data/storage
    user: root
    ports:
      - "1340:1340"
      - "8083:8083"
      - "8183:8183"
    volumes:
      - iroha3-alpha-vol:/opt/iroha_data/storage:rw
      - "./configs/peer/alpha:/config"
    init: true

volumes:
  iroha0-alpha-vol:
    name: iroha0-alpha-volume
  iroha1-alpha-vol:
    name: iroha1-alpha-volume
  iroha2-alpha-vol:
    name: iroha2-alpha-volume
  iroha3-alpha-vol:
    name: iroha3-alpha-volume
  ```
