### ISSUE TITLE
Docker CI no longer works due to GHA Cache being shut down

### ISSUE THREAD

**Issue by 0x009922** [hyperledger-iroha/iroha#5398]
Filed an issue in the upstream: https://github.com/docker/build-push-action/issues/1360

Failing action: https://github.com/hyperledger-iroha/iroha/actions/runs/14504918536/job/40692921767?pr=5380

**Comment by 0x009922** [comment]
Found documentation:

https://docs.docker.com/build/ci/github-actions/cache/#github-cache

The solution is probably to add `version: latest`:

```yaml
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v3
  with:
   version: latest
```
